# Generated by Django 5.2.4 on 2025-07-05 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, editable=False, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('access', models.CharField(max_length=30)),
            ],
        ),
    ]
